name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run E2E tests
        uses: cypress-io/github-action@v1
        with:
          build: npm run ci:buildTest
          start: npm run ci:serveTest
          wait-on: http://localhost:8080
          install: false
