name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          runTests: false
      - name: Run server
        run: npm run ci:startAngularStorybookBuild &
      - name: Run E2E tests
        uses: cypress-io/github-action@v1
        with:
          install: false
